### ISSUE TITLE
read timeout. one group seems to be defying any attempt  when run against.

### ISSUE THREAD

**Issue by bobblanchett** [IgnoredAmbience/yahoo-group-archiver#54] opened 2019-10-25 10:11 UTC
I've managed to back up dead on 100 groups successfully but one (which I've arranged with the owner to get moderator privilege plus  everything except deleting the group), chokes immediately on invocation

==
https://groups.yahoo.com/neo/groups/HOTT/info

if I can provide any information or try any fixes please let me know
I've been able to browse all sections of the group interactively to confirm access
==
File "./yahoo.py", line 619, in <module>
    archive_email(yga, save=(not args.no_save), html=args.html)
  File "./yahoo.py", line 58, in archive_email
    msg_json = yga.messages(count=count)
  File "/home/bob/Documents/ygd/yahoo-group-archiver-master/yahoogroupsapi.py", line 80, in get_json
    r = self.s.get(uri, params=opts, allow_redirects=False, timeout=15)
  File "/home/bob/.local/lib/python2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/bob/.local/lib/python2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bob/.local/lib/python2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/home/bob/.local/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='groups.yahoo.com', port=443): Read timed out. (read timeout=15)

**Comment by IgnoredAmbience** [comment] 2019-10-25 10:50
Duplicate of #15. Fix in progress today.

**Closed as completed by IgnoredAmbience** 2019-10-25 10:50 UTC
Labels: duplicate
